
limitNamespace: false

ingress:
  enabled: true
  className: nginx
  annotations:
    cert-manager.io/cluster-issuer: custom-ca-issuer
  hosts:
    - host: app-a.homelab.local
  tls:
    - secretName: kubeview-cert
      hosts:
        - app-a.homelab.local

