
limitNamespace: false

# image:
#   repository: ghcr.io/pstark-code/kubeview
#   tag: 0.2.0
#   pullPolicy: Always

ingress:
  enabled: true
  className: nginx
  annotations:
    cert-manager.io/cluster-issuer: custom-ca-issuer
  hosts:
    - host: kubeview.homelab.local
  tls:
    - secretName: kubeview-cert
      hosts:
        - kubeview.homelab.local

