apiVersion: v2
appVersion: 0.1.32
description: Kubernetes cluster visualiser and visual explorer
home: https://github.com/ctr49/kubeview
icon: https://raw.githubusercontent.com/ctr49/kubeview/master/web/client/public/favicon.png
maintainers:
- name: Ben Coleman
  url: https://benc.dev
name: kubeview
sources:
- https://github.com/ctr49/kubeview
version: 0.1.32
